export const DiseaseList = [
    { id: 1, label: "tumori / cancro / metastasi / attività tumorale" },
    { id: 2, label: "lesioni cerebrali" },
    { id: 3, label: "disturbi articolari" },
    { id: 4, label: "emorragie interne" },
    { id: 5, label: "fratture" },
    { id: 6, label: "infezioni polmonari" },
    { id: 7, label: "gravidanza" },
    { id: 8, label: "calcoli renali" },
    { id: 9, label: "malattie addominali" },
    { id: 10, label: "aritmie (incluse intermittenti)" },
    { id: 11, label: "infarto / arresto cardiaco" },
    { id: 12, label: "epilessia" },
    { id: 13, label: "disturbi neurologici" },
    { id: 14, label: "asma" },
    { id: 15, label: "malattie respiratorie (es. COPD, insufficienza respiratoria)" },
    { id: 16, label: "ulcere / problemi gastrointestinali" },
    { id: 17, label: "perdita dell’udito" },
    { id: 18, label: "glaucoma / polipi (nota: accorpati per compattezza, ma separabili)" },
    { id: 19, label: "lesioni cutanee (incluso melanoma)" },
    { id: 20, label: "osteoporosi" },
    { id: 21, label: "malattie reumatiche" },
    { id: 22, label: "infezioni sistemiche" },
    { id: 23, label: "anemia" },
    { id: 24, label: "squilibri metabolici" },
]

export const MachineList = [
    { id: 1, label: "MRI (Magnetic Resonance Imaging)", diseases: [1, 2, 3], purchaseCost: 1000, usageCost: 200 },
    { id: 2, label: "CT scan (Computed Tomography)", diseases: [4, 1, 5], purchaseCost: 1000, usageCost: 200 },
    { id: 3, label: "X-ray", diseases: [5, 6], purchaseCost: 1000, usageCost: 200 },
    { id: 4, label: "Ultrasound scanner", diseases: [7, 8, 9], purchaseCost: 1000, usageCost: 200 },
    { id: 5, label: "ECG (Electrocardiogram)", diseases: [10, 11], purchaseCost: 1000, usageCost: 200 },
    { id: 6, label: "EEG (Electroencephalogram)", diseases: [12, 13], purchaseCost: 1000, usageCost: 200 },
    { id: 7, label: "Spirometer", diseases: [14, 15], purchaseCost: 1000, usageCost: 200 },
    { id: 8, label: "Endoscope", diseases: [16, 1], purchaseCost: 1000, usageCost: 200 },
    { id: 9, label: "Colonoscope", diseases: [18, 1], purchaseCost: 1000, usageCost: 200 },
    { id: 10, label: "Mammography machine", diseases: [1], purchaseCost: 1000, usageCost: 200 },
    { id: 11, label: "PET scan (Positron Emission Tomography)", diseases: [1], purchaseCost: 1000, usageCost: 200 },
    { id: 12, label: "Holter monitor", diseases: [10], purchaseCost: 1000, usageCost: 200 },
    { id: 13, label: "Defibrillator", diseases: [11], purchaseCost: 1000, usageCost: 200 },
    { id: 14, label: "Pulse oximeter", diseases: [16, 15], purchaseCost: 1000, usageCost: 200 },
    { id: 15, label: "Audiometer", diseases: [17], purchaseCost: 1000, usageCost: 200 },
    { id: 16, label: "Tonometer (eye)", diseases: [18], purchaseCost: 1000, usageCost: 200 },
    { id: 17, label: "Dermatoscope", diseases: [1, 19], purchaseCost: 1000, usageCost: 200 },
    { id: 18, label: "Bone densitometer (DEXA scan)", diseases: [20], purchaseCost: 1000, usageCost: 200 },
    { id: 19, label: "Capillaroscope", diseases: [21], purchaseCost: 1000, usageCost: 200 },
    { id: 20, label: "Blood analyzer (hematology analyzer)", diseases: [22, 23, 24], purchaseCost: 1000, usageCost: 200 },
]

export const PatientDetailsList = [
    { gender: "f", name: "Ava" },
    { gender: "f", name: "Charlotte" },
    { gender: "f", name: "Chloe" },
    { gender: "f", name: "Ella" },
    { gender: "f", name: "Emily" },
    { gender: "f", name: "Emma" },
    { gender: "f", name: "Evelyn" },
    { gender: "f", name: "Grace" },
    { gender: "f", name: "Hannah" },
    { gender: "f", name: "Harper" },
    { gender: "f", name: "Isabella" },
    { gender: "f", name: "Jane" },
    { gender: "f", name: "Layla" },
    { gender: "f", name: "Lily" },
    { gender: "f", name: "Mia" },
    { gender: "f", name: "Nora" },
    { gender: "f", name: "Olivia" },
    { gender: "f", name: "Penelope" },
    { gender: "f", name: "Riley" },
    { gender: "f", name: "Scarlett" },
    { gender: "f", name: "Sophia" },
    { gender: "f", name: "Victoria" },
    { gender: "f", name: "Zoe" },
    { gender: "f", name: "Aria" },
    { gender: "f", name: "Madison" },
    { gender: "f", name: "Abigail" },
    { gender: "f", name: "Addison" },
    { gender: "f", name: "Alice" },
    { gender: "f", name: "Amelia" },
    { gender: "f", name: "Anna" },
    { gender: "f", name: "Ariana" },
    { gender: "f", name: "Aubrey" },
    { gender: "f", name: "Aurora" },
    { gender: "f", name: "Bella" },
    { gender: "f", name: "Brooklyn" },
    { gender: "f", name: "Camila" },
    { gender: "f", name: "Caroline" },
    { gender: "f", name: "Claire" },
    { gender: "f", name: "Delilah" },
    { gender: "f", name: "Elena" },
    { gender: "f", name: "Eliana" },
    { gender: "f", name: "Elizabeth" },
    { gender: "f", name: "Ellie" },
    { gender: "f", name: "Genesis" },
    { gender: "f", name: "Gianna" },
    { gender: "f", name: "Hailey" },
    { gender: "f", name: "Hazel" },
    { gender: "f", name: "Leah" },
    { gender: "f", name: "Lillian" },
    { gender: "f", name: "Lucy" },
    { gender: "f", name: "Luna" },
    { gender: "f", name: "Maya" },
    { gender: "f", name: "Naomi" },
    { gender: "f", name: "Natalie" },
    { gender: "f", name: "Paisley" },
    { gender: "f", name: "Piper" },
    { gender: "f", name: "Ruby" },
    { gender: "f", name: "Sadie" },
    { gender: "f", name: "Savannah" },
    { gender: "f", name: "Serenity" },
    { gender: "f", name: "Skylar" },
    { gender: "f", name: "Stella" },
    { gender: "f", name: "Taylor" },
    { gender: "f", name: "Valentina" },
    { gender: "f", name: "Violet" },
    { gender: "f", name: "Willow" },
    { gender: "f", name: "Autumn" },
    { gender: "f", name: "Faith" },
    { gender: "f", name: "Ivy" },
    { gender: "f", name: "Julia" },
    { gender: "f", name: "Kinsley" },
    { gender: "f", name: "Melanie" },
    { gender: "f", name: "Quinn" },
    { gender: "f", name: "Reagan" },
    { gender: "f", name: "Samantha" },
    { gender: "m", name: "Alexander" },
    { gender: "m", name: "Benjamin" },
    { gender: "m", name: "Caleb" },
    { gender: "m", name: "Christopher" },
    { gender: "m", name: "Daniel" },
    { gender: "m", name: "David" },
    { gender: "m", name: "Dylan" },
    { gender: "m", name: "Ethan" },
    { gender: "m", name: "Gabriel" },
    { gender: "m", name: "Henry" },
    { gender: "m", name: "Isaac" },
    { gender: "m", name: "Jack" },
    { gender: "m", name: "Jacob" },
    { gender: "m", name: "James" },
    { gender: "m", name: "John" },
    { gender: "m", name: "Joseph" },
    { gender: "m", name: "Leo" },
    { gender: "m", name: "Logan" },
    { gender: "m", name: "Lucas" },
    { gender: "m", name: "Matthew" },
    { gender: "m", name: "Michael" },
    { gender: "m", name: "Noah" },
    { gender: "m", name: "Oliver" },
    { gender: "m", name: "Samuel" },
    { gender: "m", name: "William" },
    { gender: "m", name: "Aaron" },
    { gender: "m", name: "Adam" },
    { gender: "m", name: "Adrian" },
    { gender: "m", name: "Aiden" },
    { gender: "m", name: "Andrew" },
    { gender: "m", name: "Anthony" },
    { gender: "m", name: "Asher" },
    { gender: "m", name: "Brandon" },
    { gender: "m", name: "Brian" },
    { gender: "m", name: "Charles" },
    { gender: "m", name: "Christian" },
    { gender: "m", name: "Cole" },
    { gender: "m", name: "Connor" },
    { gender: "m", name: "Dominic" },
    { gender: "m", name: "Edward" },
    { gender: "m", name: "Eli" },
    { gender: "m", name: "Elijah" },
    { gender: "m", name: "Eric" },
    { gender: "m", name: "Evan" },
    { gender: "m", name: "George" },
    { gender: "m", name: "Grayson" },
    { gender: "m", name: "Hunter" },
    { gender: "m", name: "Ian" },
    { gender: "m", name: "Jason" },
    { gender: "m", name: "Jeremiah" },
    { gender: "m", name: "Jonathan" },
    { gender: "m", name: "Jordan" },
    { gender: "m", name: "Julian" },
    { gender: "m", name: "Kevin" },
    { gender: "m", name: "Kingston" },
    { gender: "m", name: "Landon" },
    { gender: "m", name: "Levi" },
    { gender: "m", name: "Lincoln" },
    { gender: "m", name: "Mason" },
    { gender: "m", name: "Miles" },
    { gender: "m", name: "Nathan" },
    { gender: "m", name: "Nicholas" },
    { gender: "m", name: "Owen" },
    { gender: "m", name: "Parker" },
    { gender: "m", name: "Patrick" },
    { gender: "m", name: "Robert" },
    { gender: "m", name: "Ryan" },
    { gender: "m", name: "Sebastian" },
    { gender: "m", name: "Theodore" },
    { gender: "m", name: "Thomas" },
    { gender: "m", name: "Tyler" },
    { gender: "m", name: "Victor" },
    { gender: "m", name: "Wesley" },
    { gender: "m", name: "Zachary" },
    { gender: "m", name: "Xavier" }
]
