export const DiseaseList = [
    { id: 1, label: "tumori / cancro / metastasi / attività tumorale" },
    { id: 2, label: "lesioni cerebrali" },
    { id: 3, label: "disturbi articolari" },
    { id: 4, label: "emorragie interne" },
    { id: 5, label: "fratture" },
    { id: 6, label: "infezioni polmonari" },
    { id: 7, label: "gravidanza" },
    { id: 8, label: "calcoli renali" },
    { id: 9, label: "malattie addominali" },
    { id: 10, label: "aritmie (incluse intermittenti)" },
    { id: 11, label: "infarto / arresto cardiaco" },
    { id: 12, label: "epilessia" },
    { id: 13, label: "disturbi neurologici" },
    { id: 14, label: "asma" },
    { id: 15, label: "malattie respiratorie (es. COPD, insufficienza respiratoria)" },
    { id: 16, label: "ulcere / problemi gastrointestinali" },
    { id: 17, label: "perdita dell’udito" },
    { id: 18, label: "glaucoma / polipi (nota: accorpati per compattezza, ma separabili)" },
    { id: 19, label: "lesioni cutanee (incluso melanoma)" },
    { id: 20, label: "osteoporosi" },
    { id: 21, label: "malattie reumatiche" },
    { id: 22, label: "infezioni sistemiche" },
    { id: 23, label: "anemia" },
    { id: 24, label: "squilibri metabolici" },
]

export const MachineList = [
    { id: 1, label: "MRI (Magnetic Resonance Imaging)", diseases: [1, 2, 3], purchaseCost: 1000, usageCost: 200},
    { id: 2, label: "CT scan (Computed Tomography)", diseases: [4, 1, 5], purchaseCost: 1000, usageCost: 200},
    { id: 3, label: "X-ray", diseases: [5, 6], purchaseCost: 1000, usageCost: 200},
    { id: 4, label: "Ultrasound scanner", diseases: [7, 8, 9], purchaseCost: 1000, usageCost: 200},
    { id: 5, label: "ECG (Electrocardiogram)", diseases: [10, 11], purchaseCost: 1000, usageCost: 200},
    { id: 6, label: "EEG (Electroencephalogram)", diseases: [12, 13], purchaseCost: 1000, usageCost: 200},
    { id: 7, label: "Spirometer", diseases: [14, 15], purchaseCost: 1000, usageCost: 200},
    { id: 8, label: "Endoscope", diseases: [16, 1], purchaseCost: 1000, usageCost: 200},
    { id: 9, label: "Colonoscope", diseases: [18, 1], purchaseCost: 1000, usageCost: 200},
    { id: 10, label: "Mammography machine", diseases: [1]},
    { id: 11, label: "PET scan (Positron Emission Tomography)", diseases: [1], purchaseCost: 1000, usageCost: 200 },
    { id: 12, label: "Holter monitor", diseases: [10], purchaseCost: 1000, usageCost: 200 },
    { id: 13, label: "Defibrillator", diseases: [11], purchaseCost: 1000, usageCost: 200 },
    { id: 14, label: "Pulse oximeter", diseases: [16, 15], purchaseCost: 1000, usageCost: 200 },
    { id: 15, label: "Audiometer", diseases: [17], purchaseCost: 1000, usageCost: 200 },
    { id: 16, label: "Tonometer (eye)", diseases: [18], purchaseCost: 1000, usageCost: 200 },
    { id: 17, label: "Dermatoscope", diseases: [1, 19], purchaseCost: 1000, usageCost: 200 },
    { id: 18, label: "Bone densitometer (DEXA scan)", diseases: [20], purchaseCost: 1000, usageCost: 200 },
    { id: 19, label: "Capillaroscope", diseases: [21], purchaseCost: 1000, usageCost: 200 },
    { id: 20, label: "Blood analyzer (hematology analyzer)", diseases: [22, 23, 24], purchaseCost: 1000, usageCost: 200 },
]
